/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    ContactComp: typeof import('./src/components/ContactComp.vue')['default']
    IndexComp: typeof import('./src/components/IndexComp.vue')['default']
    NotFoundComp: typeof import('./src/components/NotFoundComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorkComp: typeof import('./src/components/WorkComp.vue')['default']
  }
}
