name = "www-101ta28-com"
compatibility_date = "2025-06-22"

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

# Environment variables can be added here if needed
# [vars]
# ENVIRONMENT = "production"